### ISSUE TITLE
Retry mechanism should take time elapsed into account on connection failure

### ISSUE THREAD

**Issue by xichen2020** [m3db/m3collector#34]
cc @jeromefroe 

Currently the connection retry logic is purely based on the number of times the connection is used to write data buffers, which is somewhat adhoc and hard to tune. In particular, if an agg server is down for a long time before it comes back up, it could take a long time (e.g., minutes+) for collector to even retry establishing the connection, causing the writes before then to be lost.

Alternatively, I think the retry mechanism should also take time elapsed into account. In particular, when determining whether connection should be retried, it should look at two things:
* Time since we retried establishing the connection last time (t)
* Number of writes ince we retried establishing the connection last time (n)

and compare t and n against configurable thresholds respectively (e.g., 5s and 5000 writes). This limits the impact of write losses both time-wise and write count-wise.

**Comment by jeromefroe** [comment]
#38 fixes this issue by incorporating the time since we last tried to connect into the decision of whether we should try to reconnect again.
