### ISSUE TITLE
Reset failure count on failed connection attempt

### ISSUE THREAD

**Issue by xichen2020** [m3db/m3collector#41]
cc @jeromefroe 

Currently we only reset failure counts when a retried connection attempt succeeds. As a result, if an aggregation server is down for a long time before it's removed from the placement, it takes a long time to drain the queue because the failure count would be way above the threshold at that point so every buffer write will trigger a reconnection attempt, which doesn't time out after 2s.

I think instead we should reset the failure count regardless of whether the attempt succeeds. This is not unlike a conventional time-based retrier that resets the time on a failed retry. Additionally, every time the failure threshold is bumped up, the buffers are discarded until the failure count rises up to the new threshold, so it's not consistent that after the threshold is increased to the max threshold, each write will trigger a reconnection.

**Comment by jeromefroe** [comment]
Fixed with #42
