### ISSUE TITLE
Do not merge policies during rule updates

### ISSUE THREAD

**Issue by cw9** [m3db/m3collector#46]
RN when we receive a rule update, if the policies before and after the update are the same, we merge the policies and use the older cutover time, we should just respect the update and treat them as 2 separate policies to make logic cleaner and debugging on agg tier simpler.

**Comment by xichen2020** [comment]
This is fixed in https://github.com/m3db/m3metrics/pull/113. Specifically the policies will not be merged if the two staged policies have different cutover times.
